# Generated by Django 6.0.1 on 2026-01-29 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_duration_fields'),
        ('reservations', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_minutes',
            field=models.IntegerField(default=90, help_text='Reservation duration in minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['table', 'date', 'time', 'end_time'], name='reservation_table_i_99a207_idx'),
        ),
    ]
