# Generated by Django 6.0.1 on 2026-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_alter_menuitem_options_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
