# Generated by Django 6.0.1 on 2026-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menuitem_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance in featured section (lower = first)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this item in the Featured Dishes section on homepage'),
        ),
    ]
