# Generated by Django 6.0.1 on 2026-01-30 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
