# Generated by Django 6.0.1 on 2026-01-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('category', models.CharField(choices=[('culinary', 'Culinary'), ('ambience', 'Ambience'), ('moments', 'Moments')], max_length=15)),
                ('caption', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery_images',
                'ordering': ['-date_added'],
            },
        ),
    ]
