# Generated by Django 6.0.1 on 2026-01-29 08:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_reservation_duration',
            field=models.IntegerField(default=90, help_text='Default reservation duration in minutes (30-180)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AddField(
            model_name='branch',
            name='slot_duration',
            field=models.IntegerField(default=30, help_text='Time slot interval in minutes (15-60)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
