# Generated by Django 6.0.1 on 2026-01-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_duration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_closed', models.BooleanField(default=False, help_text='Mark as closed for this day')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Operating Hours',
                'verbose_name_plural': 'Operating Hours',
                'db_table': 'branch_operating_hours',
                'ordering': ['day_of_week'],
                'unique_together': {('branch', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('holiday', 'Holiday'), ('ramadan', 'Ramadan'), ('event', 'Private Event'), ('maintenance', 'Maintenance'), ('special', 'Special Hours')], default='special', max_length=20)),
                ('is_closed', models.BooleanField(default=False, help_text='Completely closed on this date')),
                ('opening_time', models.TimeField(blank=True, help_text='Leave blank if closed', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Leave blank if closed', null=True)),
                ('note', models.CharField(blank=True, help_text="e.g., 'Eid Mubarak - Limited Menu'", max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_dates', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Special Date',
                'verbose_name_plural': 'Special Dates',
                'db_table': 'branch_special_dates',
                'ordering': ['date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
