# Generated by Django 6.0.1 on 2026-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_add_operating_hours_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
